# This file created by conda-build 26.3.0
# ------------------------------------------------

package:
  name: libmambapy
  version: 2.3.2
source:
  url: https://github.com/mamba-org/mamba/archive/refs/tags/2.3.2.tar.gz
  sha256: c969d189b0263218467b9e3b8922fcad8f7023bd8b5a981edc37e0da27cf953f
  patches: null
build:
  string: py313h0016b16_2
  run_exports:
    - libmambapy >=2.3.2,<2.4.0a0
  ignore_run_exports:
    - spdlog
  number: 2
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - cmake 4.2.3 h93052ac_0
    - libuv 1.52.0 hd0d7782_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja-base 1.13.1 h512dff2_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - vs2022_win-64 19.44.35207 hc920ad0_10
    - vs_win-64 2022.14 hc920ad0_10
    - vswhere 3.1.7 haa95532_0
    - xz 5.8.2 h53af0af_0
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2026.3.19 haa95532_0
    - cmake 4.2.3 h93052ac_0
    - cpp-expected 1.1.0 h214f63a_0
    - distro 1.9.0 py313haa95532_0
    - fmt 12.1.0 ha349831_0
    - libarchive 3.8.2 h6c023e8_0
    - libbrotlicommon 1.2.0 h907acca_0
    - libbrotlidec 1.2.0 h02c67a5_0
    - libbrotlienc 1.2.0 h483e6b9_0
    - libcurl 8.19.0 h19d1b0a_0
    - libexpat 2.7.5 hd7fb8db_0
    - libffi 3.4.4 hd77b12b_1
    - libiconv 1.18 hc89ec93_0
    - libkrb5 1.22.1 h3d06f0e_1
    - libmamba 2.3.2 hd7cc05a_2
    - libmpdec 4.0.0 h827c3e9_0
    - libsolv 0.7.30 h23a355e_2
    - libssh2 1.11.1 h2addb87_0
    - libuv 1.52.0 hd0d7782_0
    - libxml2 2.13.9 h6201b9f_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - nlohmann_json 3.11.2 h6c2663c_0
    - openssl 3.5.6 hbb43b14_0
    - packaging 26.0 py313haa95532_0
    - pcre2 10.46 h5740b90_0
    - pip 26.0.1 pyhc872135_1
    - pybind11 2.13.6 py313h214f63a_1
    - pybind11-abi 5 hd3eb1b0_0
    - pybind11-global 2.13.6 py313h214f63a_1
    - python 3.13.13 h39c999c_100_cp313
    - python_abi 3.13 3_cp313
    - reproc 14.2.4 hd77b12b_2
    - reproc-cpp 14.2.4 hd77b12b_2
    - scikit-build 0.18.1 py313h885b0b7_1
    - setuptools 72.1.0 py313haa95532_0
    - simdjson 3.10.1 h214f63a_0
    - spdlog 1.17.0 hc1cc769_0
    - sqlite 3.51.2 hee5a0db_0
    - tk 8.6.15 hf199647_0
    - tzdata 2026a he532380_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.46.3 py313haa95532_0
    - xz 5.8.2 h53af0af_0
    - yaml-cpp 0.8.0 hd77b12b_1
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  run:
    - fmt >=12.1.0,<13.0a0
    - libmamba 2.3.2 hd7cc05a_2
    - pybind11-abi ==5
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
test:
  imports:
    - libmambapy
    - libmambapy.bindings
    - libmambapy.solver
  commands:
    - python -c "import libmambapy.version; assert libmambapy.version.__version__
      == '2.3.2'"
about:
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: '


    [![Build Status](https://github.com/mamba-org/mamba/workflows/CI/badge.svg)](https://github.com/mamba-org/mamba/actions)

    [![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mamba-org/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

    [![docs](https://readthedocs.org/projects/mamba/badge/?version=latest&style=flat)](https://mamba.readthedocs.io/en/latest)


    `mamba` is a reimplementation of the conda package manager in C++.


    - parallel downloading of repository data and package files using multi-threading

    - libsolv for much faster dependency solving, a state of the art library used
    in the RPM package manager of Red Hat, Fedora and OpenSUSE

    - core parts of `mamba` are implemented in C++ for maximum efficiency


    At the same time, `mamba` utilizes the same command line parser, package installation
    and deinstallation code and transaction verification routines as `conda` to stay
    as compatible as possible.


    Mamba is part of a bigger ecosystem to make scientific packaging more sustainable.
    You can read our [announcement blog post](https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23).

    The ecosystem also consists of `quetz`, an open source `conda` package server
    and `boa`, a fast `conda` package builder.




    Please refer to the [`mamba` and `micromamba` installation guide](https://mamba.readthedocs.io/en/latest/installation.html)
    in the documentation.




    `mamba` and `micromamba` come with features on top of stock `conda`.




    To efficiently query repositories and query package dependencies you can use `mamba
    repoquery` or `micromamba repoquery`.

    See the [repoquery documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery)
    for details.




    `micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/)
    without having to install `conda-lock`. Simply invoke e.g. `micromamba create
    -n my-env -f conda-lock.yml` with an environment lockfile named `*-lock.yml` or
    `*-lock.yaml`.

    '
  dev_url: https://github.com/mamba-org/mamba
  doc_url: https://mamba.readthedocs.io/
extra:
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - ericmjl
    - wolfv
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/mamba-feedstock
  sha: 9a7ee72f90e811b37a8eaec7289be42da3136525
  task_id: ZSKDscISRZW_iRqrxvE0NQ
  task_run_id: '0'
  pbp_graph_uuid: a0d12125-5d3c-4469-b34e-d76b4c03f6a0
