# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176044737352448\httpx-feedstock\recipe, last modified Tue Oct 14 13:10:44 2025
# ------------------------------------------------

package:
  name: httpx
  version: 0.28.1
source:
  url: https://pypi.io/packages/source/h/httpx/httpx-0.28.1.tar.gz
  sha256: 75e98c5f16b0f35b567856f597f06ff2270a374470a5c2392242528e3e3e42fc
build:
  number: '1'
  script: C:\\miniconda3\\conda-bld\\httpx_1760447475275\\_h_env\\python.exe -m pip
    install . -vv --no-deps --no-build-isolation
  entry_points:
    - httpx = httpx:main
  string: py313haa95532_1
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - hatch-fancy-pypi-readme 24.1.0 py313haa95532_0
    - hatchling 1.27.0 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py313haa95532_0
    - pathspec 0.12.1 py313haa95532_0
    - pip 25.2 pyhc872135_0
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.7 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - anyio
    - certifi
    - httpcore ==1.*
    - idna
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - click >=8.0.0,<9.0.0a0
    - h2 >=3.0.0,<5.0.0a0
    - pygments >=2.0.0,<3.0.0a0
    - socksio >=1.0.0,<2.0.0a0
    - zstandard >=0.18.0
test:
  source_files:
    - tests
  imports:
    - httpx
  requires:
    - brotli-python
    - chardet
    - click
    - h2
    - pip
    - pytest
    - rich
    - trio
    - trustme
    - uvicorn
    - zstandard
  commands:
    - pip check
    - set PYTHONIOENCODING=utf8
    - httpx --help
    - pytest -vv tests -k "not ( test_socks_proxy_deprecated or test_socks_proxy or
      test_multipart_encode_files_raises_exception_with_text_mode_file or test_write_timeout
      or test_get[asyncio] or test_logging_ssl or test_get_ssl_cert_file)"
about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  description: 'HTTPX is a fully featured HTTP client library for Python 3.

    It includes an integrated command line client, has support

    for both HTTP/1.1 and HTTP/2, and provides both sync and async APIs.

    '
  doc_url: https://www.python-httpx.org
  dev_url: https://github.com/encode/httpx
extra:
  recipe-maintainers:
    - florimondmanca
    - primozgodec
    - thewchan
  final: true
  copy_test_source_files: true
