import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
//import "./globals.css";

//add
const inter = Inter({ subsets:["latin"]});

export const metadata: Metadata ={
  title:"노원구 맛집 AI 에이전트",
  description:"당신의 완벽한 시사를 위한 AI 비서"
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}
      style={{backgroundColor:"#f4f6f9"}}
      >
        {children}
      </body>
    </html>
  );
}


/*
원래 가지고 있던 html관련 설정
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>

원래 가지고 있던 폰트
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

*/
