import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
//import "./globals.css";

//add
const inter = Inter({ subsets:["latin"]});

export const metadata: Metadata ={
  title:"노원구 맛집 AI 에이전트",
  description:"당신의 완벽한 시사를 위한 AI 비서"
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
    <head>
{/* 1. 폰트어썸 (아이콘) CDN */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />
        {/* 2. 구글 Roboto 폰트 (머티리얼 디자인 최적화) CDN */}
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />
        {/* 3. MDBootstrap CSS CDN */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
          rel="stylesheet"
        />      
    </head>
      <body className={inter.className} style={{backgroundColor:"#f4f6f9"}}
      >
        {children}
      </body>
    </html>
  );
}


/*
원래 가지고 있던 html관련 설정
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>

원래 가지고 있던 폰트
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

*/
