"use client";
import styled from 'styled-components';
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import QuickConsultBar from "@/component/QuickConsultBar";
import EventPopup from "@/component/EventPopup";
import { GlobalStyle} from "@/assets/css/GlobalStyle";

//헤더에 크기때문에 픽스했을때 잘리는 크기만큼..패딩 or 마진
const MainWrapper = styled.main`
padding-top:91px;
min-height:100vh;
`;

/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="ko">
   
      <body className="min-h-full flex flex-col">
      <GlobalStyle />  
           <Header/>
      <MainWrapper>
      {children}
      </MainWrapper>
      <Footer/>
      <QuickConsultBar/>
      <EventPopup/>
      </body>
    </html>
  );
}
