import Header from "@/component/Header";
import Footer from "@/component/Footer";
import QuickConsultBar from "@/component/QuickConsultBar";
import EventModal from "@/component/EventPopup";
import EventPopup from "@/component/EventPopup";

/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="ko">
      <Header/>
      <body className="min-h-full flex flex-col">
      <main>
      {children}
      </main>
      <Footer/>
      <QuickConsultBar/>
      <EventPopup/>
      </body>
    </html>
  );
}
